## Attention With Trainable Weights

In [2]:
import torch

In [3]:
inputs = torch.nn.Embedding(4,8)

In [4]:
inputs = inputs.weight.data
inputs

tensor([[ 0.7105,  0.6528, -0.2157, -0.2809, -0.8114, -0.3414,  0.2661, -2.0810],
        [-2.2361, -0.5939,  0.2585, -0.7939,  0.7677, -0.9950, -0.8082,  1.3309],
        [ 1.0520,  1.1614,  0.9447, -1.6995,  0.2667,  1.2736, -0.9009, -0.8989],
        [-0.2590,  0.7640, -0.6376, -0.0187, -0.5093, -0.4221, -1.6806, -0.7567]])

In [ ]:
# Set dimensions
d_in = 8
d_out = 6
# Create Weight Matricies query,key,value with random entries
W_q = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_k = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_v = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [ ]:
#choose an input vector (we're using 2) and transform it into our query vector using using W_q
query = inputs[2] @ W_q
query


tensor([-0.1566,  0.8889,  1.4499,  0.2406,  1.2576,  1.5981])

In [13]:
#Calculate attention scores using the keys generates by W_k

keys = inputs @ W_k
values = inputs @ W_v
print(keys)
print(values)

tensor([[-1.0291, -1.6117, -0.8521, -1.3628, -0.3105, -1.4809],
        [-1.9449, -1.9627, -3.0443, -0.8610, -2.1701, -2.1570],
        [ 2.2391,  1.0842,  0.7962,  0.9442,  1.9731,  0.0738],
        [-2.1021, -1.8340, -1.7885, -1.9287, -1.5862, -2.4269]])
tensor([[-1.4337e-01, -1.0559e+00, -3.0322e-01, -5.6192e-01, -2.0256e+00,
         -1.5472e+00],
        [-2.2791e+00, -1.7411e+00, -3.3669e+00, -1.4210e+00, -7.3777e-01,
         -1.5988e+00],
        [ 1.3259e+00,  3.6476e-01,  9.8852e-01,  1.6805e-01, -8.3493e-01,
          9.2886e-04],
        [-1.7319e+00, -2.5013e+00, -2.5635e+00, -1.0488e+00, -2.8878e+00,
         -1.5334e+00]])


In [16]:
attention_scores = query @ keys.T
attention_scores

tensor([ -5.5919, -12.2375,   4.5941, -10.2315])

In [18]:
#normalize the scores to get the weights
attention_weights = torch.softmax(attention_scores, dim= -1)
attention_weights

tensor([3.7692e-05, 4.8987e-08, 9.9996e-01, 3.6416e-07])

In [ ]:
#Make sure you did it right
attention_weights.sum()

tensor(1.0000)

In [ ]:
# make the context vector
context_vector = attention_weights @ values
context_vector

tensor([ 1.3259e+00,  3.6471e-01,  9.8847e-01,  1.6802e-01, -8.3498e-01,
         8.6987e-04])